### ISSUE TITLE
hub: Whyjay's notebook failed to save, website refresh made notebook state change over 1h be lost

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#57]
@whyjz reported a very serious malfunction and I'm trying to summarize what is know here.

## Background

- User storage is mounted via EFS, and Whyjay was working against that storage.
- A notebook failed to save over ~1h time, both automatically and manually
- The file manager on the left side in JupyterLab acted out and failed to report files, but the folders were still showing.
- Whyjay was able to execute code, render markdown, run bash commands, etc. In other words, Whyjay's server was functional and responsive, but the mounted storage misbehaved somehow it seems.
- Whyjay reported that refreshing the page (ctrl+r) made the notebook save-able again, but that the unsaved progress had been lost.

## Conclusions

Since the issue went away by refreshing the browser, it seems to me that JupyterLab's storage interaction with the actual user server acted up. The state of the notebook is within the browser, and saving it means to pass that information to the user server, which in turn saves it to disk.

I think a key point to further understand this issue is also to inspect the browser javascript console, are there errors showing there when pressing the save button? We have observed a lot of errors in the hub server as well and those probably hint of the issue but I'm not catching up on the issue from reading them yet.

## Wayjay's server's error logs

Note that the error that is repeated here in the logs were repeated over and over for ~100 times or so. I just included a few repetitions.

<details>
<summary>Whyjay's server's error logs are here</summary>

```
[I 2021-06-10 07:11:57.750 SingleUserNotebookApp contentsmanager:141] Saving getdata.ipynb
TermSocket.open: 1
TermSocket.open: Opened 1
[W 2021-06-10 07:15:11.860 SingleUserNotebookApp zmqhandlers:179] WebSocket ping timeout after 119846 ms.
Websocket closed
[I 2021-06-10 07:15:23.482 SingleUserNotebookApp kernelspec:337] Removing existing kernelspec in /home/jovyan/.local/share/jupyter/kernels/conda-env-.conda-jme-py
[I 2021-06-10 07:15:23.591 SingleUserNotebookApp kernelspec:341] Installed kernelspec conda-env-.conda-jme-py in /home/jovyan/.local/share/jupyter/kernels/conda-env-.conda-jme-py
[I 2021-06-10 07:16:08.527 SingleUserNotebookApp handlers:164] Saving file at /Projects/Github/toy-research-workflow/docs/icesat2-crevasses/ideas.md
Task exception was never retrieved
future: <Task finished name='Task-69420' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py:1100> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1102, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1104, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-69422' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py:1100> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1102, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1104, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-69458' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py:1100> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1102, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1104, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-69518' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py:1100> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1102, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1104, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-69533' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py:1100> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 1102, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed
```

</details>

**Comment by whyjz** [comment]
Thanks @consideRatio for documenting this! I will let you know when it happens next time (hopefully not...)

**Comment by whyjz** [comment]
As the JupyterLab version is updated and I haven't seen this happening for a few months, I am closing this issue now until it happens again.
